server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
spring:
  application:
    name: zuul-service
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password: 683280
    timeout: 1000
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
zuul:
  routes:
    tss:
      path: /tss/**
      serviceId: ribbon-service
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

