server:
  port: 1111

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/



